export default [
    {
        Status: "Invalid",
        "Quote Number": "993aaa0",
        "Agreement Name": "AIVNQVW",
        "Agreement Type": "SPA",
        "Distributor Name": "GQTNCCPAN",
        "Effective Date": "2/22/2021",
        "Expiration Date": "2/9/2020",
        "Created Date": "3/24/2021",
        "Days Until Expiration": "FUVRXICAB",
    },
    {
        Status: "Invalid",
        "Quote Number": "4179222",
        "Agreement Name": "DAOHX",
        "Agreement Type": "SPA",
        "Distributor Name": "HBHUTWC",
        "Effective Date": "1/3/2020",
        "Expiration Date": "2/25/2020",
        "Created Date": "2020/7/28",
        "Days Until Expiration": "GBGTRL",
    },
    {
        Status: "Invalid",
        "Quote Number": "b628196",
        "Agreement Name": "VMGQBKUKQ",
        "Agreement Type": "SPA",
        "Distributor Name": "VGMUBKTJ",
        "Effective Date": "1/20/2020",
        "Expiration Date": "4/12/2020",
        "Created Date": "1/8/2022",
        "Days Until Expiration": "CGKKGA",
    },
    {
        Status: "Published",
        "Quote Number": "9b9bf9f",
        "Agreement Name": "QLFDLWQ",
        "Agreement Type": "SPA",
        "Distributor Name": "YHSDGBQ",
        "Effective Date": "12/23/2020",
        "Expiration Date": "3/28/2022",
        "Created Date": "5/5/2022",
        "Days Until Expiration": "OVXEQD",
    },
    {
        Status: "Invalid",
        "Quote Number": "7e38f2aa",
        "Agreement Name": "UXNLSE",
        "Agreement Type": "SPA",
        "Distributor Name": "VGPHF",
        "Effective Date": "1/9/2021",
        "Expiration Date": "12/1/2020",
        "Created Date": "3/26/2022",
        "Days Until Expiration": "KHDVUK",
    },
    {
        Status: "Invalid",
        "Quote Number": "d04cf77",
        "Agreement Name": "ZFVLFT",
        "Agreement Type": "SPA",
        "Distributor Name": "IDJUMDFT",
        "Effective Date": "5/24/2020",
        "Expiration Date": "5/17/2020",
        "Created Date": "6/24/2021",
        "Days Until Expiration": "PIVKZA",
    },
    {
        Status: "Published",
        "Quote Number": "f42ed81",
        "Agreement Name": "YBURR",
        "Agreement Type": "SPA",
        "Distributor Name": "AYAWBQS",
        "Effective Date": "9/9/2021",
        "Expiration Date": "4/29/2022",
        "Created Date": "7/23/2020",
        "Days Until Expiration": "ZPRRQXSYS",
    },
    {
        Status: "Published",
        "Quote Number": "dc3c6a44",
        "Agreement Name": "KJEPCMFFS",
        "Agreement Type": "SPA",
        "Distributor Name": "DWTKWMOP",
        "Effective Date": "5/6/2020",
        "Expiration Date": "1/7/2021",
        "Created Date": "8/3/2021",
        "Days Until Expiration": "BCQJTG",
    },
    {
        Status: "Published",
        "Quote Number": "b8f23675",
        "Agreement Name": "AHSOZHS",
        "Agreement Type": "SPA",
        "Distributor Name": "KNXHH",
        "Effective Date": "2/13/2021",
        "Expiration Date": "10/6/2021",
        "Created Date": "10/14/2020",
        "Days Until Expiration": "GIHVGDMWD",
    },
    {
        Status: "Published",
        "Quote Number": "21fc75d",
        "Agreement Name": "IDYDE",
        "Agreement Type": "SPA",
        "Distributor Name": "RBLQG",
        "Effective Date": "8/30/2021",
        "Expiration Date": "12/24/2020",
        "Created Date": "12/15/2020",
        "Days Until Expiration": "DTRXNQC",
    },
    {
        Status: "Published",
        "Quote Number": "9b4783e5",
        "Agreement Name": "XQKJKKJX",
        "Agreement Type": "SPA",
        "Distributor Name": "KXKBUV",
        "Effective Date": "8/31/2021",
        "Expiration Date": "11/25/2021",
        "Created Date": "8/22/2020",
        "Days Until Expiration": "DZHAVXXJR",
    },
    {
        Status: "Pending",
        "Quote Number": "7198398d",
        "Agreement Name": "OVJCEJD",
        "Agreement Type": "SPA",
        "Distributor Name": "VGWCJLYJ",
        "Effective Date": "5/20/2021",
        "Expiration Date": "1/14/2021",
        "Created Date": "10/31/2020",
        "Days Until Expiration": "ARRGEF",
    },
    {
        Status: "Published",
        "Quote Number": "f222032",
        "Agreement Name": "YDAVM",
        "Agreement Type": "SPA",
        "Distributor Name": "JBZSJI",
        "Effective Date": "9/8/2020",
        "Expiration Date": "10/19/2021",
        "Created Date": "4/28/2020",
        "Days Until Expiration": "GESKI",
    },
    {
        Status: "Published",
        "Quote Number": "7dad86d",
        "Agreement Name": "ZYCEHIZA",
        "Agreement Type": "SPA",
        "Distributor Name": "EWVAOYAML",
        "Effective Date": "2/5/2020",
        "Expiration Date": "6/30/2021",
        "Created Date": "1/14/2022",
        "Days Until Expiration": "BOJMGJKU",
    },
    {
        Status: "Invalid",
        "Quote Number": "6455d239",
        "Agreement Name": "CNCJDTS",
        "Agreement Type": "SPA",
        "Distributor Name": "LUIILDSW",
        "Effective Date": "7/16/2021",
        "Expiration Date": "2/22/2021",
        "Created Date": "7/29/2021",
        "Days Until Expiration": "ZKPDF",
    },
    {
        Status: "Invalid",
        "Quote Number": "73736923",
        "Agreement Name": "HLZHCI",
        "Agreement Type": "SPA",
        "Distributor Name": "WDXZDHLGY",
        "Effective Date": "4/22/2021",
        "Expiration Date": "1/6/2020",
        "Created Date": "9/2/2021",
        "Days Until Expiration": "NXZHDE",
    },
    {
        Status: "Published",
        "Quote Number": "2ce48f3",
        "Agreement Name": "XVYHEKE",
        "Agreement Type": "SPA",
        "Distributor Name": "ORKXVW",
        "Effective Date": "4/21/2022",
        "Expiration Date": "3/6/2020",
        "Created Date": "4/14/2022",
        "Days Until Expiration": "CVHXSZQH",
    },
    {
        Status: "Published",
        "Quote Number": "a114907",
        "Agreement Name": "ARTFAQIS",
        "Agreement Type": "SPA",
        "Distributor Name": "NKHXSZ",
        "Effective Date": "6/12/2020",
        "Expiration Date": "5/14/2021",
        "Created Date": "6/3/2021",
        "Days Until Expiration": "JGFCZLZJ",
    },
    {
        Status: "Published",
        "Quote Number": "998a6b1",
        "Agreement Name": "YLHZRT",
        "Agreement Type": "SPA",
        "Distributor Name": "FLKYVWIVA",
        "Effective Date": "5/15/2021",
        "Expiration Date": "12/4/2021",
        "Created Date": "1/20/2022",
        "Days Until Expiration": "LQIHMPJJQ",
    },
    {
        Status: "Invalid",
        "Quote Number": "866e29db",
        "Agreement Name": "ECZWR",
        "Agreement Type": "SPA",
        "Distributor Name": "WRJMK",
        "Effective Date": "12/6/2021",
        "Expiration Date": "2/27/2021",
        "Created Date": "2/3/2021",
        "Days Until Expiration": "EZEQYN",
    },
    {
        Status: "Invalid",
        "Quote Number": "1a354f2e",
        "Agreement Name": "VVNCJYBCP",
        "Agreement Type": "SPA",
        "Distributor Name": "JFNOPIO",
        "Effective Date": "3/30/2020",
        "Expiration Date": "5/9/2022",
        "Created Date": "7/31/2020",
        "Days Until Expiration": "ZDHEDE",
    },
    {
        Status: "Pending",
        "Quote Number": "a63a20e",
        "Agreement Name": "SJHKHLWCD",
        "Agreement Type": "SPA",
        "Distributor Name": "PLWGM",
        "Effective Date": "12/5/2020",
        "Expiration Date": "10/4/2020",
        "Created Date": "2/22/2022",
        "Days Until Expiration": "NOIXZOI",
    },
    {
        Status: "Invalid",
        "Quote Number": "a9b99f2b",
        "Agreement Name": "MVPEMIDH",
        "Agreement Type": "SPA",
        "Distributor Name": "NOAEMPBZ",
        "Effective Date": "6/21/2021",
        "Expiration Date": "11/20/2021",
        "Created Date": "12/12/2020",
        "Days Until Expiration": "OXMIYTZYH",
    },
    {
        Status: "Invalid",
        "Quote Number": "3fe4925f",
        "Agreement Name": "BHMEXPZR",
        "Agreement Type": "SPA",
        "Distributor Name": "KUMRYCCW",
        "Effective Date": "3/6/2020",
        "Expiration Date": "12/26/2021",
        "Created Date": "3/29/2020",
        "Days Until Expiration": "MNAOCZI",
    },
    {
        Status: "Pending",
        "Quote Number": "4ea31e0",
        "Agreement Name": "LWHKFRUP",
        "Agreement Type": "SPA",
        "Distributor Name": "VXNZQVB",
        "Effective Date": "1/12/2022",
        "Expiration Date": "7/8/2021",
        "Created Date": "11/21/2020",
        "Days Until Expiration": "HUBBLMIF",
    },
    {
        Status: "Published",
        "Quote Number": "d548ce08",
        "Agreement Name": "SKJLNGOSB",
        "Agreement Type": "SPA",
        "Distributor Name": "MZBDSW",
        "Effective Date": "8/20/2020",
        "Expiration Date": "8/21/2020",
        "Created Date": "5/4/2022",
        "Days Until Expiration": "VEKHGNGV",
    },
    {
        Status: "Published",
        "Quote Number": "5254c625",
        "Agreement Name": "RAAWULGSM",
        "Agreement Type": "SPA",
        "Distributor Name": "ZRAWOQLU",
        "Effective Date": "8/28/2021",
        "Expiration Date": "9/15/2020",
        "Created Date": "10/25/2020",
        "Days Until Expiration": "SDOED",
    },
    {
        Status: "Published",
        "Quote Number": "a6188c6",
        "Agreement Name": "XEIQMXPB",
        "Agreement Type": "SPA",
        "Distributor Name": "KNUVHRMWM",
        "Effective Date": "3/27/2021",
        "Expiration Date": "10/12/2021",
        "Created Date": "3/23/2020",
        "Days Until Expiration": "QZIFE",
    },
    {
        Status: "Published",
        "Quote Number": "96a1c37a",
        "Agreement Name": "MFTLVYS",
        "Agreement Type": "SPA",
        "Distributor Name": "QOKGSK",
        "Effective Date": "3/24/2020",
        "Expiration Date": "5/20/2020",
        "Created Date": "1/4/2020",
        "Days Until Expiration": "YFAQAL",
    },
    {
        Status: "Published",
        "Quote Number": "8900d95a",
        "Agreement Name": "MFIQPIAAJ",
        "Agreement Type": "SPA",
        "Distributor Name": "YDVDYL",
        "Effective Date": "5/18/2021",
        "Expiration Date": "1/9/2022",
        "Created Date": "4/11/2020",
        "Days Until Expiration": "DJQHT",
    },
    {
        Status: "Pending",
        "Quote Number": "77c831e",
        "Agreement Name": "ZOBGVDI",
        "Agreement Type": "SPA",
        "Distributor Name": "RSBGEJ",
        "Effective Date": "3/12/2021",
        "Expiration Date": "3/26/2021",
        "Created Date": "6/18/2020",
        "Days Until Expiration": "DCJOWIDA",
    },
    {
        Status: "Pending",
        "Quote Number": "5a7e310",
        "Agreement Name": "FYRGBUZ",
        "Agreement Type": "SPA",
        "Distributor Name": "ZJWNRQGD",
        "Effective Date": "10/16/2020",
        "Expiration Date": "1/1/2020",
        "Created Date": "11/24/2020",
        "Days Until Expiration": "WRCAG",
    },
    {
        Status: "Pending",
        "Quote Number": "036aca8",
        "Agreement Name": "ZBEKM",
        "Agreement Type": "SPA",
        "Distributor Name": "VQENYL",
        "Effective Date": "11/25/2020",
        "Expiration Date": "1/30/2021",
        "Created Date": "4/5/2022",
        "Days Until Expiration": "SCMJKPTUE",
    },
    {
        Status: "Published",
        "Quote Number": "bf5a8709",
        "Agreement Name": "AOOBZ",
        "Agreement Type": "SPA",
        "Distributor Name": "SKEHURZW",
        "Effective Date": "1/8/2021",
        "Expiration Date": "4/27/2020",
        "Created Date": "11/23/2020",
        "Days Until Expiration": "RZXPXR",
    },
    {
        Status: "Published",
        "Quote Number": "690a5c8",
        "Agreement Name": "OBUAM",
        "Agreement Type": "SPA",
        "Distributor Name": "VIZIID",
        "Effective Date": "9/9/2020",
        "Expiration Date": "5/23/2020",
        "Created Date": "3/25/2022",
        "Days Until Expiration": "BQAUIZMFC",
    },
    {
        Status: "Invalid",
        "Quote Number": "48a30004",
        "Agreement Name": "ZNUEYZNAT",
        "Agreement Type": "SPA",
        "Distributor Name": "CYRTPEFS",
        "Effective Date": "10/27/2021",
        "Expiration Date": "12/7/2021",
        "Created Date": "5/22/2021",
        "Days Until Expiration": "GHAXKIWA",
    },
    {
        Status: "Invalid",
        "Quote Number": "f6e2348",
        "Agreement Name": "RXJQFWWA",
        "Agreement Type": "SPA",
        "Distributor Name": "XNIYDUI",
        "Effective Date": "4/24/2022",
        "Expiration Date": "11/12/2020",
        "Created Date": "5/5/2021",
        "Days Until Expiration": "HINFOGK",
    },
    {
        Status: "Pending",
        "Quote Number": "43386a5",
        "Agreement Name": "WECGF",
        "Agreement Type": "SPA",
        "Distributor Name": "UDREZEN",
        "Effective Date": "7/27/2020",
        "Expiration Date": "8/21/2020",
        "Created Date": "3/6/2020",
        "Days Until Expiration": "ROYYFHWQU",
    },
    {
        Status: "Pending",
        "Quote Number": "c32f2be",
        "Agreement Name": "QWGPXV",
        "Agreement Type": "SPA",
        "Distributor Name": "QPWGWCQV",
        "Effective Date": "1/11/2021",
        "Expiration Date": "6/20/2020",
        "Created Date": "12/30/2020",
        "Days Until Expiration": "LNKTZFHMT",
    },
    {
        Status: "Pending",
        "Quote Number": "ffd547f",
        "Agreement Name": "BHOELOP",
        "Agreement Type": "SPA",
        "Distributor Name": "AJNFWOI",
        "Effective Date": "2/5/2021",
        "Expiration Date": "6/8/2020",
        "Created Date": "4/4/2020",
        "Days Until Expiration": "BVKBTPF",
    },
    {
        Status: "Published",
        "Quote Number": "8955f64",
        "Agreement Name": "KNMAK",
        "Agreement Type": "SPA",
        "Distributor Name": "CWAEJY",
        "Effective Date": "6/22/2021",
        "Expiration Date": "4/8/2022",
        "Created Date": "11/26/2021",
        "Days Until Expiration": "FNJCSID",
    },
    {
        Status: "Pending",
        "Quote Number": "b223fd9f",
        "Agreement Name": "YZESXW",
        "Agreement Type": "SPA",
        "Distributor Name": "UXPBHZWN",
        "Effective Date": "1/10/2022",
        "Expiration Date": "8/18/2021",
        "Created Date": "9/25/2020",
        "Days Until Expiration": "RLJEY",
    },
    {
        Status: "Published",
        "Quote Number": "b0be99c",
        "Agreement Name": "KHEMFPIJ",
        "Agreement Type": "SPA",
        "Distributor Name": "UENBO",
        "Effective Date": "12/5/2020",
        "Expiration Date": "8/7/2021",
        "Created Date": "3/26/2022",
        "Days Until Expiration": "EDNBC",
    },
    {
        Status: "Published",
        "Quote Number": "46be0bb",
        "Agreement Name": "KCTPGWLS",
        "Agreement Type": "SPA",
        "Distributor Name": "PUGJUPO",
        "Effective Date": "10/11/2021",
        "Expiration Date": "1/24/2020",
        "Created Date": "10/8/2020",
        "Days Until Expiration": "BWNINOMO",
    },
    {
        Status: "Published",
        "Quote Number": "ed22597a",
        "Agreement Name": "CWXWT",
        "Agreement Type": "SPA",
        "Distributor Name": "ZOOBIU",
        "Effective Date": "5/21/2021",
        "Expiration Date": "6/12/2020",
        "Created Date": "7/24/2020",
        "Days Until Expiration": "BLKZAORYC",
    },
    {
        Status: "Pending",
        "Quote Number": "82a775ae",
        "Agreement Name": "FPVYFFTC",
        "Agreement Type": "SPA",
        "Distributor Name": "XPUQQDCI",
        "Effective Date": "3/15/2022",
        "Expiration Date": "2/5/2020",
        "Created Date": "2/7/2020",
        "Days Until Expiration": "HMFSXGYDW",
    },
    {
        Status: "Invalid",
        "Quote Number": "58b7a3f",
        "Agreement Name": "XLHYD",
        "Agreement Type": "SPA",
        "Distributor Name": "YQSZENYB",
        "Effective Date": "1/5/2020",
        "Expiration Date": "6/25/2020",
        "Created Date": "3/5/2022",
        "Days Until Expiration": "XRLJQR",
    },
    {
        Status: "Published",
        "Quote Number": "67920dc1",
        "Agreement Name": "YKIFJ",
        "Agreement Type": "SPA",
        "Distributor Name": "KDXWS",
        "Effective Date": "3/8/2022",
        "Expiration Date": "9/26/2020",
        "Created Date": "1/30/2021",
        "Days Until Expiration": "JAUSTNX",
    },
    {
        Status: "Invalid",
        "Quote Number": "9f6d38c",
        "Agreement Name": "UZJJOUKX",
        "Agreement Type": "SPA",
        "Distributor Name": "DQMMLDSJY",
        "Effective Date": "5/3/2021",
        "Expiration Date": "4/4/2022",
        "Created Date": "12/13/2021",
        "Days Until Expiration": "OUUACVF",
    },
    {
        Status: "Pending",
        "Quote Number": "0d6cae63",
        "Agreement Name": "WZZGJU",
        "Agreement Type": "SPA",
        "Distributor Name": "ZYTGF",
        "Effective Date": "10/28/2020",
        "Expiration Date": "2/2/2022",
        "Created Date": "9/20/2020",
        "Days Until Expiration": "OZMJQ",
    },
];
